### ISSUE TITLE
Run private testnet

### ISSUE THREAD

**Issue by adamkrawczyk** [SiaFoundation/siad#15]
Hi, 

I can't find information about how to run a testnet. 

My concept is to create a local sub-chain for storing data on my private chain - is it even possible?

Real-life example: 
Minimum 3 hosts lending storage (some rpi-s) 
Some nodes renting storage (my pc/my phone)

All this working out of sia chain. Available only when using a modified version of your client app. 

Also, the thing I'm wondering about is how to run this based on the VPN connection layer -> no public address for any of the hosts 

What is your opinion and how about coin utility on this sub-chain. In this model in my opinion it's needless. 

Best,
Adam

**Comment by n8maninger** [comment]
The token is integral to the functioning of the network and storage contracts. You could fork Sia and start mining your own private chain or you can run a temporary local testnet using Sia-Ant-Farm https://gitlab.com/NebulousLabs/Sia-Ant-Farm. 

It doesn't really make sense to run such a small private network, by default you need at least 30 hosts to store data on. You might consider a distributed FS like Ceph. That seems like a much better fit if the token is unnecessary and hosts aren't supposed to be publicly accessible.

I'm going to go ahead and close this since it isn't an actual issue.
