### ISSUE TITLE
Loss of data - unrecoverable?

### ISSUE THREAD

**Issue by jytou** [SiaFoundation/siad#64]
Hi,
I have lost a full location storage (folder). Gone. Impossible to restore. Is all my storage corrupted now or is there a way to only lose what was stored in that location?
What I have done is simply deleted the corresponding folder from the contractmanager.json file, and everything seems to run ok. Of course the contracts attached to the data stored on that location will be lost, but it represented less than 1% of all my storage. So I'm fine losing a few contracts if the rest is still ok... or is it just hopeless and I should scrap it all?
Thanks!

**Comment by n8maninger** [comment]
When you lose a folder, you only lose the data stored in that folder. Modifying the JSON files is highly likely to put your host in a bad state. It sounds like your host is OK, but for future reference, to remove a lost folder, you should force remove it.

Host Manager: click the delete icon on the storage page and check "Force" in the modal.
cli: `siac host folder remove --force /path/to/folder`
Sia-UI: in the built-in terminal `host folder remove --force /path/to/folder`.

Closing this since it's not an issue with Sia, you can get quicker support in our Discord https://discord.gg/sia
