### ISSUE TITLE
Docker image stops workig after some time

### ISSUE THREAD

**Issue by back2basic** [SiaFoundation/siad#65]
I switched yesterday to this repository for running the Sia host in docker but the siac command doesn't give any output after running the image for 2 hours.
A restart of the container fixes the issue but that's not acceptable.

Do more hosters have this issue ?

**Comment by llann** [comment]
Same issue but on a longer period. For me it crashes every week. I was using the [nebulouselabs ](https://registry.hub.docker.com/r/nebulouslabs/sia/) image before and it was working like a charm, but since 1.5.7 I'm using the official one and I have a lot of issues. Also, sometimes, my host is "unreachable" from siastats even if my external monitoring says that the host is always online. Before that image change I've been online for months with 100% uptime.

**Comment by back2basic** [comment]
closed this since the issue was not the docker image but it was the upgrade to 1.5.7  that introduced host lockups when completing contracts.
this is fixed in 1.5.8
